services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "gradeusdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1235"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server/config:/app/config
      - ./server/src:/app/src
      - ./server/test:/app/test
    ports:
      - 5000:5000

networks:
  postgres:
    driver: bridge
