const Router = require("express")
const router = new Router()
const userRouter = require("./userRouter")
const roleRouter = require("./roleRouter")
const subjectRouter = require("./subjectRouter")
const labGroupRouter = require("./labGroupRouter")
const projectRouter = require("./projectRouter")
const projectGradeCategoriesRouter = require("./projectGradeCategoriesRouter")
const gradeRouter = require("./gradeRouter")
const categoriesGradeRouter = require("./categoriesGradeRouter")

router.use("/user", userRouter)
router.use("/role", roleRouter)
router.use("/subject", subjectRouter)
router.use("/lab_group", labGroupRouter)
router.use("/project", projectRouter)
router.use("/project_grade", projectGradeCategoriesRouter)
router.use("/grade", gradeRouter)
router.use("/category_grade", categoriesGradeRouter)

module.exports = router
